### ISSUE TITLE
Add some CTA buttons and measure their clicks

### ISSUE THREAD

**Issue by groovecoder** [mozilla/shield-study-privacy#12]
Job Story: When the user leaves the study (by choice? by default?), show them actions to take and measure the clicks, so we can learn which actions indicate retention and/or growth.

Some example actions:

* "Make Firefox my default browser"
* "Share Firefox" (Twitter/Facebook link?)

**Comment by groovecoder** [comment]
This makes more sense to put into a "Thank You" page if we can.

**Comment by jsavory** [comment]
Ok I've created a Thank You page that includes both the default browser action and the share buttons. Are we able to check if the user is already using Firefox as their default browser? (Otherwise I'll take out that line) and if they are I'm guessing we could take out that button and text.

Here's the link:
https://drive.google.com/a/mozilla.com/file/d/0B8kj4Mlm-HJeUXZMMjdHTHdZY2s/view?usp=sharing

**Comment by groovecoder** [comment]
@gregglind - In https://github.com/mozilla/shield-study-privacy/compare/add-cta-thankyou-page, I'm trying to open a `thankyou.html` page during the study "`cleanup`" method. But it looks like the add-on (and its `thankyou.html` file) have already been removed by the time `cleanup` runs, so the tab opens to an empty page?

**Comment by groovecoder** [comment]
So this could be quite tricky to do inside the add-on before the un-install/disable of the shield study happens.

Do we think CTA buttons/links on the post-study survey are sufficient? We would want/need to use a post-study survey "platform" that allows us to add these links/buttons and measure the conversion rate on them.

Hmm ...
